# -*- coding: utf-8 -*-
"""si618_lab6_czj.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pTrog7_goV5pzJFhFeEYXx4DGk7X39vn
"""

from pyspark.sql import SQLContext
from pyspark import SparkContext
sc = SparkContext(appName="lecture6")
sqlContext = SQLContext(sc)

nfl_df = sqlContext.read.json("hdfs:///data/umsi618f20/lab6/NFLPlaybyPlay2015.json")
nfl_df.registerTempTable('nfl')

#q1 = sqlContext.sql('select z.defensiveteam,(z.defscore-z.posscore)/z.cnt as delta from (select * from (select distinct posteam, sum(defteamscore) over(partition by posteam) as posscore from nfl) a \
#join (select distinct DefensiveTeam, sum(defteamscore) over(partition by defensiveteam) as defscore from nfl) b \
#on a.posteam=b.defensiveteam join (select DefensiveTeam as team1, count(distinct gameid) as cnt from nfl group by defensiveteam) c on b.defensiveteam=c.team1) z order by delta desc')

q1 = sqlContext.sql('select a.defensiveteam, (sum(a.earn)-sum(a.loss))/count(distinct(a.Gameid)) as mdp from(select def.Gameid, defensiveteam, loss, earn from (select GameId, posteam, sum(defteamscore) as loss from nfl group by posteam, GameId) pos \
join (select GameId, defensiveteam, sum(defteamscore) as earn from nfl group by defensiveteam, GameId) def on pos.Gameid = def.Gameid and pos.posteam = def.defensiveteam) a group by a.defensiveteam order by mdp desc') 

q1.rdd.map(lambda i: '\t'.join(str(j) for j in i)).saveAsTextFile('labq1')

qq = sqlContext.sql('select z.t1, (z.p_yards/z.rush_p) as ratio from (select *from (SELECT DefensiveTeam as t1, SUM(PenaltyYards) AS p_yards FROM nfl WHERE PlayType IN ("Pass","Sack")  \
                             GROUP BY DefensiveTeam) a join (select defensiveteam, playtype, sum(PenaltyYards) as rush_p from nfl where playtype in ("Run") group by defensiveteam, playtype) b \
                             on a.t1 = b.defensiveteam) z order by ratio')
qq.rdd.map(lambda i: '\t'.join(str(j) for j in i)).saveAsTextFile('labq2')

#qq = sqlContext.sql('select z.t1, (sum(z.p_yards)/sum(z.r_yards)) as ratio from (SELECT a.DefensiveTeam as t1, a.playtype ap, SUM(a.PenaltyYards) as p_yards ,b.playtype bp, sum(b.PenaltyYards) as r_yards FROM nfl a \
#                             join nfl b on a.DefensiveTeam = b.DefensiveTeam \
#                             WHERE a.PlayType IN ("Pass","Sack") and b.Playtype in("Run") \
#                            GROUP BY a.DefensiveTeam, a.playtype, b.playtype) z group by z.t1, z.bp order by ratio')
#spark-submit --master yarn --num-executors 16 --executor-memory 1g --executor-cores 8 si618_lab6_czj.py